[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fastapi-crud-generator"
version = "0.1.0"
description = "CRUD route generator for FastAPI"
requires-python = ">=3.11"
dependencies = [
    "fastapi",
    "pydantic",
]

[project.optional-dependencies]
sqlmodel = ["sqlmodel"]

[tool.hatch.build.targets.wheel]
packages = ["fastapi_crud_generator"]

[tool.ruff]
line-length = 79

[dependency-groups]
dev = [
    "pytest",
    "sqlmodel",
    "ipykernel>=7.2.0",
]
docs = [
    "mkdocs-material",
    "mkdocstrings[python]",
    "griffe-inherited-docstrings",
]
