"""Tests for SQLModelAdapter.generate_*_schema methods.

Each schema type has its own test class. The shared SQLModel fixtures
are defined at module level so the SQLAlchemy metadata is registered once.
"""
import uuid
from datetime import datetime
from typing import ClassVar

from sqlalchemy import Column, DateTime, func
from sqlmodel import Field, SQLModel

from fastapi_crud_generator.config import CRUDConfigDict
from fastapi_crud_generator.orm.sqlmodel import SQLModelAdapter
from sqlmodel.main import FieldInfoMetadata


async def _fake_session():
    yield None


def make_adapter(model) -> SQLModelAdapter:
    return SQLModelAdapter(get_session=_fake_session, model=model)


# ---------------------------------------------------------------------------
# Test models
# ---------------------------------------------------------------------------

class Article(SQLModel, table=True):
    __tablename__ = 'test_schema_gen_article'

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    title: str
    content: str
    # exclude=True means "don't include in API responses" — output marker
    internal_notes: str | None = Field(default=None, exclude=True)
    # server_default — value is generated by the DB, not by the application
    created_at: datetime | None = Field(
        default=None,
        sa_column=Column(DateTime(timezone=True), server_default=func.now()),
    )


class ArticleWithConfig(SQLModel, table=True):
    __tablename__ = 'test_schema_gen_article_with_config'

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    title: str
    content: str
    summary: str | None = None

    crud_config: ClassVar[CRUDConfigDict] = CRUDConfigDict(
        public_fields={'title', 'summary'},
        create_fields={'title', 'content'},
        update_fields={'title', 'content', 'summary'},
    )


# ---------------------------------------------------------------------------
# generate_public_schema
# ---------------------------------------------------------------------------

class TestGeneratePublicSchema:

    def test_default_excludes_fields_marked_with_exclude(self):
        schema = make_adapter(Article).generate_public_schema()
        assert 'internal_notes' not in schema.model_fields

    def test_default_includes_server_default_fields(self):
        # server_default is an input detail, not a reason to hide from public
        schema = make_adapter(Article).generate_public_schema()
        assert 'created_at' in schema.model_fields

    def test_explicit_fields_trusted_as_is(self):
        schema = make_adapter(Article).generate_public_schema(fields={'title'})
        assert set(schema.model_fields) == {'title'}

    def test_crud_config_public_fields_used_when_no_args(self):
        schema = make_adapter(ArticleWithConfig).generate_public_schema()
        assert set(schema.model_fields) == {'title', 'summary'}

    def test_explicit_fields_arg_overrides_crud_config(self):
        schema = make_adapter(ArticleWithConfig).generate_public_schema(
            fields={'content'},
        )
        assert set(schema.model_fields) == {'content'}

    def test_orm_metadata_stripped_from_result(self):
        schema = make_adapter(Article).generate_public_schema()
        for field_info in schema.model_fields.values():
            orm_meta = [m for m in field_info.metadata
                        if isinstance(m, FieldInfoMetadata)]
            assert not orm_meta


# ---------------------------------------------------------------------------
# generate_create_schema
# ---------------------------------------------------------------------------

class TestGenerateCreateSchema:

    def test_default_excludes_pk_and_server_default(self):
        schema = make_adapter(Article).generate_create_schema()
        assert 'id' not in schema.model_fields         # PK — auto-generated
        assert 'created_at' not in schema.model_fields  # server_default

    def test_exclude_true_fields_still_accepted_as_input(self):
        # exclude=True = "don't serialize to output", not "reject as input"
        schema = make_adapter(Article).generate_create_schema()
        assert 'internal_notes' in schema.model_fields

    def test_required_fields_stay_required(self):
        schema = make_adapter(Article).generate_create_schema()
        assert schema.model_fields['title'].is_required()

    def test_crud_config_create_fields_used_when_no_args(self):
        schema = make_adapter(ArticleWithConfig).generate_create_schema()
        assert set(schema.model_fields) == {'title', 'content'}

    def test_explicit_fields_used_without_automatic_exclusions(self):
        # When caller specifies fields explicitly, we trust their list as-is
        schema = make_adapter(Article).generate_create_schema(
            fields={'title', 'content'},
        )
        assert set(schema.model_fields) == {'title', 'content'}


# ---------------------------------------------------------------------------
# generate_update_schema
# ---------------------------------------------------------------------------

class TestGenerateUpdateSchema:

    def test_default_same_field_set_as_create(self):
        adapter = make_adapter(Article)
        create_fields = set(adapter.generate_create_schema().model_fields)
        update_fields = set(adapter.generate_update_schema().model_fields)
        assert create_fields == update_fields

    def test_all_fields_optional_for_patch_semantics(self):
        schema = make_adapter(Article).generate_update_schema()
        for field_info in schema.model_fields.values():
            assert not field_info.is_required()

    def test_crud_config_update_fields_used_when_no_args(self):
        schema = make_adapter(ArticleWithConfig).generate_update_schema()
        assert set(schema.model_fields) == {'title', 'content', 'summary'}

    def test_explicit_fields_all_become_optional(self):
        schema = make_adapter(Article).generate_update_schema(
            fields={'title', 'content'},
        )
        assert not schema.model_fields['title'].is_required()
        assert not schema.model_fields['content'].is_required()
