from abc import ABC, abstractmethod

from pydantic import BaseModel


class ORMAdapterBase(ABC):
    """Abstract base class for ORM adapters.

    An adapter bridges a specific ORM and ``CRUDCollection`` by implementing
    schema generation and request handler methods. Each ORM has its own
    adapter subclass (e.g. ``SQLModelAdapter``) that translates the generic
    interface into ORM-specific queries and schema introspection.
    """

    @abstractmethod
    def generate_public_schema(
        self,
        fields: set[str] | None = None,
        base_fields: set[str] | None = None,
    ) -> type[BaseModel]:
        """Build a Pydantic model for API read responses.

        Fields are resolved in priority order:

        1. ``fields`` argument (main) + ``base_fields`` — unioned together.
        2. ``crud_config.public_fields`` (main) + ``crud_config.base_fields``
           — used when the corresponding explicit argument is omitted.
        3. Adapter default — all non-excluded fields plus the primary key.
           Applied only when **both** main and base resolve to nothing.
           If only ``base_fields`` is set, the result is ``base_fields``
           alone; the default is skipped.

        Args:
            fields: Main field set. Overrides ``crud_config.public_fields``
                and adapter defaults.
            base_fields: Extra fields unioned with the main set. Overrides
                ``crud_config.base_fields`` when provided.

        Returns:
            A Pydantic model class containing only the resolved fields.
        """

    @abstractmethod
    def generate_create_schema(
        self,
        fields: set[str] | None = None,
        base_fields: set[str] | None = None,
    ) -> type[BaseModel]:
        """Build a Pydantic model for object creation payloads.

        Fields are resolved in priority order:

        1. ``fields`` argument (main) + ``base_fields`` — unioned together.
        2. ``crud_config.create_fields`` (main) + ``crud_config.base_fields``
           — used when the corresponding explicit argument is omitted.
        3. Adapter default — all fields except primary keys and fields whose
           values are generated by the database (e.g. ``server_default``).
           Applied only when **both** main and base resolve to nothing.
           If only ``base_fields`` is set, the result is ``base_fields``
           alone; the default is skipped.

        Note: fields marked ``exclude=True`` are **not** excluded here —
        that marker controls serialization of responses, not input acceptance.

        Args:
            fields: Main field set. Overrides ``crud_config.create_fields``
                and adapter defaults.
            base_fields: Extra fields unioned with the main set. Overrides
                ``crud_config.base_fields`` when provided.

        Returns:
            A Pydantic model class containing only the resolved fields.
        """

    @abstractmethod
    def generate_update_schema(
        self,
        fields: set[str] | None = None,
        base_fields: set[str] | None = None,
    ) -> type[BaseModel]:
        """Build a Pydantic model for partial update (PATCH) payloads.

        Uses the same field resolution logic as ``generate_create_schema``,
        but every field is made optional so clients only send what they
        want to change.

        Args:
            fields: Main field set. Overrides ``crud_config.update_fields``
                and adapter defaults.
            base_fields: Extra fields unioned with the main set. Overrides
                ``crud_config.base_fields`` when provided.

        Returns:
            A Pydantic model class where every field is optional.
        """

    @abstractmethod
    def generate_include_schema(self) -> type[BaseModel]:
        """Build a query schema for selecting which relationships to include.

        The returned model should have an ``include`` field that accepts a
        list of valid relationship names. FastAPI uses it to validate that
        only existing relationships are requested as query parameters.
        """

    @abstractmethod
    async def get_many_handler(self):
        """Handle GET / — return a paginated, filtered, sorted list.

        Applies filtering, sorting, and relationship inclusion to the base
        queryset, then paginates the result.
        """

    @abstractmethod
    async def get_one_handler(self):
        """Handle GET /{pk} — return a single object by primary key.

        Raises 404 if no object with the given primary key exists.
        """

    @abstractmethod
    async def create_one_handler(self):
        """Handle POST / — persist a new object and return it."""

    @abstractmethod
    async def create_many_handler(self):
        """Handle POST /bulk — persist multiple objects at once."""

    @abstractmethod
    async def update_one_handler(self):
        """Handle PATCH /{pk} — partially update an existing object.

        Only fields present in the request payload are updated.
        Raises 404 if no object with the given primary key exists.
        """

    @abstractmethod
    async def update_many_handler(self):
        """Handle PATCH /bulk — partially update multiple objects at once."""

    @abstractmethod
    async def delete_one_handler(self):
        """Handle DELETE /{pk} — delete an object by primary key.

        Returns the deleted object. Raises 404 if it does not exist.
        """
