from abc import ABC, abstractmethod

from pydantic import BaseModel

from fastapi_crud_generator.paginator import PaginatorBase
from fastapi_crud_generator.schemas import PaginatorPage, ParentRef


class ORMAdapterBase(ABC):
    """Abstract base class for ORM adapters.

    An adapter bridges a specific ORM and ``CRUDCollection`` by implementing
    schema generation and pure data-access methods. Each ORM has its own
    adapter subclass (e.g. ``SQLModelAdapter``) that translates the generic
    interface into ORM-specific queries and schema introspection.

    HTTP concerns (routing, status codes, dependency injection) live in
    ``CRUDCollection``, not here.
    """

    paginator_class: type = PaginatorBase

    @abstractmethod
    def generate_public_schema(
        self,
        fields: set[str] | None = None,
        base_fields: set[str] | None = None,
    ) -> type[BaseModel]:
        """Build a Pydantic model for API read responses.

        Fields are resolved in priority order:

        1. ``fields`` argument (main) + ``base_fields`` — unioned together.
        2. ``crud_config.public_fields`` (main) + ``crud_config.base_fields``
           — used when the corresponding explicit argument is omitted.
        3. Adapter default — all non-excluded fields plus the primary key.
           Applied only when **both** main and base resolve to nothing.
           If only ``base_fields`` is set, the result is ``base_fields``
           alone; the default is skipped.

        Args:
            fields: Main field set. Overrides ``crud_config.public_fields``
                and adapter defaults.
            base_fields: Extra fields unioned with the main set. Overrides
                ``crud_config.base_fields`` when provided.

        Returns:
            A Pydantic model class containing only the resolved fields.

        """

    @abstractmethod
    def generate_create_schema(
        self,
        fields: set[str] | None = None,
        base_fields: set[str] | None = None,
    ) -> type[BaseModel]:
        """Build a Pydantic model for object creation payloads.

        Fields are resolved in priority order:

        1. ``fields`` argument (main) + ``base_fields`` — unioned together.
        2. ``crud_config.create_fields`` (main) + ``crud_config.base_fields``
           — used when the corresponding explicit argument is omitted.
        3. Adapter default — all fields except primary keys and fields whose
           values are generated by the database (e.g. ``server_default``).
           Applied only when **both** main and base resolve to nothing.
           If only ``base_fields`` is set, the result is ``base_fields``
           alone; the default is skipped.

        Note: fields marked ``exclude=True`` are **not** excluded here —
        that marker controls serialization of responses, not input acceptance.

        Args:
            fields: Main field set. Overrides ``crud_config.create_fields``
                and adapter defaults.
            base_fields: Extra fields unioned with the main set. Overrides
                ``crud_config.base_fields`` when provided.

        Returns:
            A Pydantic model class containing only the resolved fields.

        """

    @abstractmethod
    def generate_update_schema(
        self,
        fields: set[str] | None = None,
        base_fields: set[str] | None = None,
    ) -> type[BaseModel]:
        """Build a Pydantic model for partial update (PATCH) payloads.

        Uses the same field resolution logic as ``generate_create_schema``,
        but every field is made optional so clients only send what they
        want to change.

        Args:
            fields: Main field set. Overrides ``crud_config.update_fields``
                and adapter defaults.
            base_fields: Extra fields unioned with the main set. Overrides
                ``crud_config.base_fields`` when provided.

        Returns:
            A Pydantic model class where every field is optional.

        """

    def get_model_name(self) -> str:
        """Return the lowercase model name, or empty string if unavailable."""
        return ""

    @abstractmethod
    def generate_pk_schema(self) -> type[BaseModel]:
        """Build a Pydantic model containing only the primary key fields."""

    @abstractmethod
    def generate_include_schema(self) -> type[BaseModel]:
        """Build a query schema for selecting which relationships to include.

        The returned model should have an ``include`` field that accepts a
        list of valid relationship names. FastAPI uses it to validate that
        only existing relationships are requested as query parameters.
        """

    @abstractmethod
    async def get_one(
        self,
        pk_values: BaseModel,
        include_data: BaseModel,
        parent_refs: list[ParentRef] | None = None,
    ) -> object | None:
        """Return a single object by primary key, or None if not found."""

    @abstractmethod
    async def get_many(
        self,
        filter_data: BaseModel,
        sort_data: BaseModel,
        include_data: BaseModel,
        paginator: PaginatorBase,
        parent_refs: list[ParentRef] | None = None,
    ) -> PaginatorPage:
        """Return a paginated, filtered, sorted list."""

    @abstractmethod
    async def create_one(
        self,
        data: BaseModel,
        parent_refs: list[ParentRef] | None = None,
    ) -> object:
        """Persist a new object and return it."""

    @abstractmethod
    async def update_one(
        self,
        pk_values: BaseModel,
        data: BaseModel,
        parent_refs: list[ParentRef] | None = None,
    ) -> None:
        """Update an existing object by primary key."""

    @abstractmethod
    async def delete_one(
        self,
        pk_values: BaseModel,
        parent_refs: list[ParentRef] | None = None,
    ) -> object | None:
        """Delete an object by primary key and return it, or None."""
