"""ORM adapter for pure SQLAlchemy async (DeclarativeBase, not SQLModel)."""
from __future__ import annotations

from collections.abc import AsyncGenerator, Callable
from contextlib import asynccontextmanager
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, create_model
from pydantic_core import PydanticUndefined

from fastapi_crud_generator.config import CRUDConfigDict
from fastapi_crud_generator.orm.base import ORMAdapterBase
from fastapi_crud_generator.paginator import PaginatorBase
from fastapi_crud_generator.schemas import (
    NotFoundError,
    PaginatorPage,
    ParentNotFoundError,
    ParentRef,
)

try:
    import sqlalchemy as sa
    from sqlalchemy.ext.asyncio import AsyncSession
    from sqlalchemy.orm import (
        DeclarativeBase,
        joinedload,
        noload,
        selectinload,
    )
except ImportError:
    SQLALCHEMY_INSTALLED = False
else:
    SQLALCHEMY_INSTALLED = True


class _OrmBase(BaseModel):
    """Shared config for all generated schemas: read from ORM attributes."""
    model_config = ConfigDict(from_attributes=True)


def _col_python_type(col_type: Any) -> type:
    """Return the Python type for a SQLAlchemy column type."""
    try:
        return col_type.python_type
    except NotImplementedError:
        return str


def _field_tuple(
    col: Any,
    *,
    optional: bool = False,
) -> tuple[type, Any]:
    """Return (annotation, default) for a Pydantic field from an SA column."""
    py_type = _col_python_type(col.type)
    if optional:
        return py_type | None, None
    if col.nullable:
        return py_type | None, None
    return py_type, PydanticUndefined


def _schema_from_cols(
    name: str,
    model: type,
    field_names: set[str],
    *,
    optional: bool = False,
    extra: dict[str, tuple] | None = None,
) -> type[BaseModel]:
    """Build a Pydantic model from SA mapper column attrs."""
    mapper = sa.inspect(model)
    fields: dict[str, tuple] = {}
    for attr in mapper.column_attrs:
        col_name = attr.key
        if col_name not in field_names:
            continue
        col = attr.columns[0]
        fields[col_name] = _field_tuple(col, optional=optional)
    if extra:
        fields.update(extra)
    return create_model(name, __base__=_OrmBase, **fields)


class SQLAlchemyPaginator(PaginatorBase):
    async def paginate(
        self,
        session: AsyncSession,
        query: Any,
    ) -> PaginatorPage:
        count = await session.scalar(
            sa.select(sa.func.count()).select_from(query.subquery())
        )
        rows = await session.execute(
            query.limit(self.limit).offset(self.offset)
        )
        return {
            "count": count,
            "page": self.page,
            "per_page": self.per_page,
            "data": rows.scalars().all(),
        }


class SQLAlchemyAdapter(ORMAdapterBase):
    """ORM adapter for SQLAlchemy async (DeclarativeBase) models.

    Works with any model that inherits from SQLAlchemy's
    ``DeclarativeBase``. Schemas are generated by introspecting
    the SA mapper — no Pydantic annotations required on the model.

    Args:
        get_session: Async generator yielding an ``AsyncSession``.
        model: The declarative ORM model class to operate on.

    """

    get_session: Callable[
        [], AsyncGenerator[AsyncSession, None]
    ] = None
    model: type | None = None
    paginator_class = SQLAlchemyPaginator

    def __init__(
        self,
        *,
        get_session: Callable[
            [], AsyncGenerator[AsyncSession, None]
        ] = None,
        model: type | None = None,
    ) -> None:
        if not SQLALCHEMY_INSTALLED:
            raise ImportError("sqlalchemy is not installed")
        self.get_session = get_session or self.__class__.get_session
        self.model = model or self.model
        if not self.get_session:
            raise ValueError("get_session is required")
        if not self.model:
            raise ValueError("model is required")

    @asynccontextmanager
    async def session(self) -> AsyncGenerator[AsyncSession, None]:
        async for s in self.get_session():
            yield s

    def get_model_name(self) -> str:
        return self.model.__name__.lower()

    def get_crud_config(self) -> CRUDConfigDict:
        return getattr(self.model, "crud_config", CRUDConfigDict())

    def get_pk_field_names(self) -> set[str]:
        return {
            col.name
            for col in self.model.__table__.primary_key.columns
        }

    def get_server_generated_field_names(self) -> set[str]:
        result: set[str] = set()
        mapper = sa.inspect(self.model)
        for attr in mapper.column_attrs:
            col = attr.columns[0]
            if col.server_default is not None:
                result.add(attr.key)
        return result

    def get_default_public_fields(self) -> set[str]:
        mapper = sa.inspect(self.model)
        return {attr.key for attr in mapper.column_attrs}

    def get_default_create_fields(
        self,
        exclude_related: list[type] | None = None,
    ) -> set[str]:
        pk_names = self.get_pk_field_names()
        related_tables = {m.__table__ for m in (exclude_related or [])}
        fk_from_related = {
            fk.parent.name
            for fk in self.model.__table__.foreign_keys
            if fk.column.table in related_tables
        }
        # A PK is auto-generated only when:
        # - it is the sole integer PK on the table (autoincrement="auto"), OR
        # - autoincrement=True is explicitly set, OR
        # - a Python-side default is declared.
        single_pk = len(pk_names) == 1
        auto_pks: set[str] = set()
        mapper = sa.inspect(self.model)
        for attr in mapper.column_attrs:
            col = attr.columns[0]
            if attr.key not in pk_names:
                continue
            explicitly_auto = col.autoincrement is True
            auto_by_rule = (
                col.autoincrement == "auto"
                and single_pk
                and isinstance(col.type, sa.Integer)
            )
            has_default = col.default is not None
            if explicitly_auto or auto_by_rule or has_default:
                auto_pks.add(attr.key)
        excluded = auto_pks | fk_from_related | self.get_server_generated_field_names()
        return {
            attr.key
            for attr in mapper.column_attrs
            if attr.key not in excluded
        }

    def get_default_update_fields(self) -> set[str]:
        excluded = (
            self.get_pk_field_names()
            | self.get_server_generated_field_names()
        )
        mapper = sa.inspect(self.model)
        return {
            attr.key
            for attr in mapper.column_attrs
            if attr.key not in excluded
        }

    def _effective_fields(
        self,
        fields: set[str] | None,
        base_fields: set[str] | None,
        default: set[str],
    ) -> set[str]:
        crud = self.get_crud_config()
        main = fields or (crud.public_fields or None)
        base = base_fields or (crud.base_fields or None)
        if main is None and base is None:
            return default
        return (main or set()) | (base or set())

    def _flat_public_schema(
        self,
        fields: set[str] | None = None,
        base_fields: set[str] | None = None,
    ) -> type[BaseModel]:
        effective = self._effective_fields(
            fields,
            base_fields,
            self.get_default_public_fields() | self.get_pk_field_names(),
        )
        return _schema_from_cols(
            f"{self.model.__name__}Public", self.model, effective,
        )

    def generate_public_schema(
        self,
        fields: set[str] | None = None,
        base_fields: set[str] | None = None,
    ) -> type[BaseModel]:
        base = self._flat_public_schema(fields, base_fields)
        mapper = sa.inspect(self.model)
        rel_fields: dict[str, tuple] = {}
        for rel_name, rel_prop in mapper.relationships.items():
            related_cls = rel_prop.mapper.class_
            tmp = object.__new__(SQLAlchemyAdapter)
            tmp.model = related_cls
            nested = tmp._flat_public_schema()
            field_type = list[nested] if rel_prop.uselist else nested
            rel_fields[rel_name] = (field_type | None, None)
        if not rel_fields:
            return base
        return create_model(
            base.__name__, __base__=base, **rel_fields,
        )

    def generate_create_schema(
        self,
        fields: set[str] | None = None,
        base_fields: set[str] | None = None,
        exclude_related: list[type] | None = None,
    ) -> type[BaseModel]:
        crud = self.get_crud_config()
        main = fields or (crud.create_fields or None)
        base = base_fields or (crud.base_fields or None)
        if main is None and base is None:
            effective = self.get_default_create_fields(exclude_related)
        else:
            effective = (main or set()) | (base or set())
        return _schema_from_cols(
            f"{self.model.__name__}Create", self.model, effective,
        )

    def generate_update_schema(
        self,
        fields: set[str] | None = None,
        base_fields: set[str] | None = None,
    ) -> type[BaseModel]:
        crud = self.get_crud_config()
        main = fields or (crud.update_fields or None)
        base = base_fields or (crud.base_fields or None)
        if main is None and base is None:
            effective = self.get_default_update_fields()
        else:
            effective = (main or set()) | (base or set())
        return _schema_from_cols(
            f"{self.model.__name__}Update",
            self.model,
            effective,
            optional=True,
        )

    def generate_pk_schema(self) -> type[BaseModel]:
        return _schema_from_cols(
            f"{self.model.__name__}PK",
            self.model,
            self.get_pk_field_names(),
        )

    def generate_include_schema(self) -> type[BaseModel]:
        mapper = sa.inspect(self.model)
        rel_names = tuple(mapper.relationships.keys())
        if not rel_names:
            return create_model(f"{self.model.__name__}Include")
        literal_type = Literal.__getitem__(rel_names)
        return create_model(
            f"{self.model.__name__}Include",
            include=(list[literal_type] | None, None),
        )

    def _apply_parent_refs(
        self, stmt: Any, parent_refs: list[ParentRef],
    ) -> Any:
        for parent_ref in parent_refs:
            stmt = stmt.join(parent_ref.model)
            for field, value in parent_ref.pk_values.model_dump().items():
                stmt = stmt.where(
                    getattr(parent_ref.model, field) == value,
                )
        return stmt

    def get_base_list_queryset(
        self, parent_refs: list[ParentRef] | None = None,
    ) -> Any:
        stmt = sa.select(self.model)
        if not parent_refs:
            return stmt
        return self._apply_parent_refs(stmt, parent_refs)

    def get_base_single_queryset(
        self, parent_refs: list[ParentRef] | None = None,
    ) -> Any:
        stmt = sa.select(self.model)
        if not parent_refs:
            return stmt
        return self._apply_parent_refs(stmt, parent_refs)

    def apply_queryset_filter(self, stmt: Any, filter_data: BaseModel) -> Any:
        for key, value in filter_data.model_dump(exclude_unset=True).items():
            stmt = stmt.where(getattr(self.model, key) == value)
        return stmt

    def apply_queryset_sort(self, stmt: Any, sort_data: BaseModel) -> Any:
        if len(type(sort_data).model_fields) != 1:
            raise ValueError("Only one sort argument is supported")
        sort_dict = sort_data.model_dump(exclude_unset=True)
        if not sort_dict:
            return stmt
        sort_value = next(iter(sort_dict.values()))
        if not isinstance(sort_value, list):
            sort_value = [sort_value]
        added: list[str] = []
        for value in sort_value:
            field, *direction = value.split(":", 2)
            if field not in added:
                added.append(field)
                attr = getattr(self.model, field)
                if direction and direction[0] == "desc":
                    attr = sa.desc(attr)
                stmt = stmt.order_by(attr)
        return stmt

    def include_related(self, stmt: Any, include_data: BaseModel) -> Any:
        requested = set(getattr(include_data, "include", None) or [])
        mapper = sa.inspect(self.model)
        for rel_name, rel_prop in mapper.relationships.items():
            rel_attr = getattr(self.model, rel_name)
            if rel_name in requested:
                opt = (
                    selectinload(rel_attr)
                    if rel_prop.uselist
                    else joinedload(rel_attr)
                )
            else:
                opt = noload(rel_attr)
            stmt = stmt.options(opt)
        return stmt

    def _nullify_unloaded_relations(
        self, instance: Any, include_data: BaseModel,
    ) -> None:
        requested = set(getattr(include_data, "include", None) or [])
        mapper = sa.inspect(self.model)
        for rel_name in mapper.relationships.keys():
            if rel_name not in requested:
                instance.__dict__[rel_name] = None

    def _nullify_all_relations(self, instance: Any) -> None:
        """Set all relationship attributes to None (for create/delete)."""
        mapper = sa.inspect(self.model)
        for rel_name in mapper.relationships.keys():
            instance.__dict__[rel_name] = None

    def _instance_to_dict(self, instance: Any) -> dict:
        """Convert an ORM instance to a plain dict for serialization.

        SA instances carry instrumentation state in __dict__; we strip the
        private SA key and include only column + already-nullified relation
        attrs so that TypeAdapter(Any).dump_json() can handle the result.
        """
        mapper = sa.inspect(self.model)
        col_names = {attr.key for attr in mapper.column_attrs}
        rel_names = set(mapper.relationships.keys())
        result: dict = {}
        for key, val in instance.__dict__.items():
            if key.startswith("_sa_"):
                continue
            if key in col_names or key in rel_names:
                result[key] = val
        return result

    def _fk_values_from_parent(self, parent_ref: ParentRef) -> dict:
        parent_table = parent_ref.model.__table__
        result: dict = {}
        for fk in self.model.__table__.foreign_keys:
            if fk.column.table is parent_table:
                value = getattr(
                    parent_ref.pk_values, fk.column.name, None,
                )
                if value is not None:
                    result[fk.parent.name] = value
        return result

    def _verify_parent_chain_stmt(
        self, parent_refs: list[ParentRef],
    ) -> Any:
        direct = parent_refs[0]
        stmt = sa.select(direct.model)
        stmt = self._apply_parent_refs(stmt, parent_refs[1:])
        for field, value in direct.pk_values.model_dump().items():
            stmt = stmt.where(
                getattr(direct.model, field) == value,
            )
        return stmt

    async def get_one(
        self,
        pk_values: BaseModel,
        include_data: BaseModel,
        parent_refs: list[ParentRef] | None = None,
    ) -> Any | None:
        stmt = self.get_base_single_queryset(parent_refs=parent_refs)
        for key, value in pk_values.model_dump().items():
            stmt = stmt.where(getattr(self.model, key) == value)
        stmt = self.include_related(stmt, include_data)
        async with self.session() as session:
            result = (await session.execute(stmt)).scalars().first()
            if result is not None:
                self._nullify_unloaded_relations(result, include_data)
            return result

    async def get_many(
        self,
        filter_data: BaseModel,
        sort_data: BaseModel,
        include_data: BaseModel,
        paginator: SQLAlchemyPaginator,
        parent_refs: list[ParentRef] | None = None,
    ) -> PaginatorPage:
        stmt = self.get_base_list_queryset(parent_refs=parent_refs)
        stmt = self.apply_queryset_filter(stmt, filter_data)
        stmt = self.apply_queryset_sort(stmt, sort_data)
        stmt = self.include_related(stmt, include_data)
        async with self.session() as session:
            page = await paginator.paginate(session, stmt)
            for item in page["data"]:
                self._nullify_unloaded_relations(item, include_data)
            return page

    async def create_one(
        self,
        data: BaseModel,
        parent_refs: list[ParentRef] | None = None,
    ) -> Any:
        data_dict = data.model_dump()
        async with self.session() as session:
            if parent_refs:
                stmt = self._verify_parent_chain_stmt(parent_refs)
                if (
                    await session.execute(stmt)
                ).scalars().first() is None:
                    raise ParentNotFoundError
                for ref in parent_refs:
                    data_dict.update(self._fk_values_from_parent(ref))
            item = self.model(**data_dict)
            session.add(item)
            await session.commit()
            await session.refresh(item)
            self._nullify_all_relations(item)
            return self._instance_to_dict(item)

    async def update_one(
        self,
        pk_values: BaseModel,
        data: BaseModel,
        parent_refs: list[ParentRef] | None = None,
    ) -> None:
        in_scope = True
        async with self.session() as session:
            if parent_refs:
                check = self.get_base_single_queryset(
                    parent_refs=parent_refs,
                )
                for key, value in pk_values.model_dump().items():
                    check = check.where(
                        getattr(self.model, key) == value,
                    )
                in_scope = (
                    await session.execute(check)
                ).scalars().first() is not None
            if in_scope:
                new_values = data.model_dump(exclude_unset=True)
                stmt = sa.update(self.model)
                for key, value in pk_values.model_dump().items():
                    stmt = stmt.where(
                        getattr(self.model, key) == value,
                    )
                stmt = stmt.values(**new_values)
                await session.execute(stmt)
                await session.commit()
        if not in_scope:
            raise NotFoundError

    async def delete_one(
        self,
        pk_values: BaseModel,
        parent_refs: list[ParentRef] | None = None,
    ) -> Any | None:
        stmt = self.get_base_single_queryset(parent_refs=parent_refs)
        for key, value in pk_values.model_dump().items():
            stmt = stmt.where(getattr(self.model, key) == value)
        async with self.session() as session:
            result = (await session.execute(stmt)).scalars().first()
            if result is None:
                return None
            await session.delete(result)
            await session.commit()
        self._nullify_all_relations(result)
        return self._instance_to_dict(result)
